package com.equoterapia.dominio.enums;

public enum GruposMuscularesEnum {
    TONUS_NORMAL,
    DISCRETO_AUMENTO_DO_TONUS,
    AUMENTO_MAIS_PRONUNCIADO_DO_TONUS,
    AUMENTO_CONSIDERAVEL_TONUS,
    ARTICULACAO_AFETADA_RIGIDA_EM_FLEXAO_OU_EXTENSAO;
}
